name: Build Local

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore NuGet packages
        run: nuget restore "GMTPC.Tool.sln"

      - name: Build Release
        run: |
          msbuild "GMTPC.Tool.sln" /p:Configuration=Release /t:Rebuild /v:minimal

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: GMTPC.Tool-Build
          path: bin/Release/net48/
          retention-days: 7
